### ISSUE TITLE
Adding new node: unintuitive where in the list you are

### ISSUE THREAD

**Issue by isaac-dunn** [cambridge-alpha-team/unvisual-frontend#12]
If I remember correctly, when you press + to add a new node, the first item in the list of options (loop) is selected. However, instead of reading this out, at the moment, just "What would you like to add?" is read, not "loop". So, if you press down, then you end up on the second element of the list (play), and it might not occur to you that there's something above it.

**Comment by tjvr** [comment]
The underlying problem here is that in our implementation, the interface for selecting code to add uses an entirely different code path than the one for navigating the tree. (This is why things like "item X of Y" don't work for the "adding" mode, amongst others.) We should think about how to make the interface more consistent.

**Comment by RusticFlare** [comment]
This is fixed for 'add' in PR #26

**Comment by tjvr** [comment]
This is still an issue. After adding code, the new node is announced immediately; there is no acknowledgement that something was added. This makes it unclear what happened, or where we are now.

A brief message like “added X below Y”, before reading the name of the new node, would be nice.
